name: Test proxy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/dealmore/dealmore-build-images/lambdaci:nodejs12.x
    steps:
      - uses: actions/checkout@v2

      - name: Jest
        run: |
          yarn --frozen-lockfile --cache-folder .yarn
          yarn test

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn
            **/node_modules
          key: ${{ runner.os }}-test
